[supabase]
SUPABASE_URL = "https://liwosofcfuebugxrycto.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxpd29zb2ZjZnVlYnVneHJ5Y3RvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk4NzM2OTUsImV4cCI6MjA4NTQ0OTY5NX0.lzg0Nyc-I3Umvna1Vt4K24m8DDRUjjgMOPqHIsPqSrA"

[positions]
password = "Vietnamdog123"

